### ISSUE TITLE
Porque arrendondar os valores?

### ISSUE THREAD

**Issue by Figuera** [tchiluanda/rtn#2]
Antes de mais nada, parabéns pelo trabalho! Sou servidor afastado da STN e sempre quis trabalhar em um projeto similar a esse, estava testando algumas funcionalidades e no geral achei a qualidade do projeto excepcional.

No entanto eu notei que os valores de Receita estão arredondados, algum motivo em particular para isso? O arquivo original do RTN tem várias casas decimais mas os dados baixados não possuem nenhuma.

Eu pergunto porque o resultado parece intencional, essa é a linha que arredonda os valores da Receita:

`series_temporais_analise$Valor <-round(as.numeric(series_temporais_analise$Valor),0)`

**Comment by fernandobarbalho** [comment]
Obrigado pelo comentário. Creio que não haja maiores problemas em tirar o arredondamento, mas ainda assim vou analisar o impacto disso e ficando tudo certo vou excluir essa linha.
Aliás, isso me faz lembrar que eu preciso colocar no readme que os dados são em R$ milhões.

**Comment by fernandobarbalho** [comment]
Exclusão de todos os arredondamentos.

Commit: 414d30baf874b4d9a30c7dfff4506e22a98689af

**Comment by Figuera** [comment]
Faz um link para o commit (deve ter como fazer no momento de fechar o issue). É útil para revisão.
