### ISSUE TITLE
Na limpeza dos nomes das legendas excluir os sinais de adição

### ISSUE THREAD

**Issue by fernandobarbalho** [tchiluanda/rtn#4]

**Comment by Figuera** [comment]
Posso adicionar algo aqui?

Seria útil separar as Rubricas entre "Codigo" e "Nome".

Atualmente eu estou usando o seguinte código:

```
  receitas  <- rtn::get_full_data()
  receitas %<>% mutate(
    rubrica_code = str_extract(Rubrica, '[\\d,\\.]*'), 
    rubrica_name = str_extract(Rubrica, '[A-Z,a-z].*$'))
```

Dessa maneira eu posso selecionar uma rubrica muito mais facilmente usando apenas o código:

```
receitas %>% filter(rubrica_code == "1.1.03.1")
```

O método não é perfeito, em parte porque o código usados pelo STN são mais complexos do que o necessário mas também porque eles são menos estáveis do que eu gostaria. Nesse final de semana os códigos parecem ter mudado de padrão, ele era "1.1.3.1" mas se tornou "1.1.03.1". Ainda assim é melhor do que selecionar pelo nome completo.

**Comment by fernandobarbalho** [comment]
Símbolos excluídos dos nomes das rubricas.

Commit: 414d30baf874b4d9a30c7dfff4506e22a98689af
